import Header from '@/components/Header'
import '../public/globals.css'
import { Inter } from 'next/font/google'
import HomePage from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portafolio Autómatas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <div className='flex flex-col justify-center items-center'>
            {children}
        </div>
      </body>
    </html>
  )
} 
